spring:
  application:
    name: demo
  flyway:
    user: root
    password: root
    clean-disabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

hibernate:
  discriminator:
    ignore_explicit_for_joined: true