spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
